---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.example.com
  resources:
  - scalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.example.com
  resources:
  - scalers/finalizers
  verbs:
  - update
- apiGroups:
  - api.example.com
  resources:
  - scalers/status
  verbs:
  - get
  - patch
  - update
