apiVersion: api.example.com/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: scaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  start: 10
  end: 15
  replicas: 5
  deployments:
    - name: nginx
      namespace: default
